window.LIGHTER_ALIASES = {
  "Dunhill": ["Alfred Dunhill", "Dunhill London"],
  "S.T. Dupont": ["ST Dupont", "S T Dupont", "Dupont"],
  "Thorens": ["Thorens Switzerland", "Thorens Swiss"],
  "Early Ronson / Art Metal Works": ["Ronson", "Art Metal Works", "AMW", "Ronson Art Metal Works"],
  "Evans": ["Evans Case Company"],
  "KW / Karl Wieden / KAWEE": ["KW", "Karl Wieden", "KAWEE", "Kawee"],
  "Hahway / HW": ["Hahway", "H.W.", "HW"],
  "IMCO": ["IMCO Austria", "Julius Meister & Co"],
  "Mylflam": ["Mylflam Zunder", "Mylflam Zünder"],
  "Ibelo / Jbelo": ["Ibelo", "Jbelo"],
  "Colibri": ["Colibri of London"],
  "Flaminaire / Quercia": ["Flaminaire", "Quercia"],
  "IM Corona": ["Corona", "IM Corona Old Boy"],
  "Windmill": ["Windmill Japan"],
  "Sarome": ["Sarome Japan"],
  "Prince": ["Prince Japan"],
  "Maruman": ["Maruman Japan"],
  "Zippo": ["Zippo Manufacturing Company"],
  "ZORRO": ["Zorro Lighter", "Zorro 打火機"],
  "Tsubota Pearl": ["Tsubota", "Pearl Japan"],
  "Douglass": ["Douglas Field L", "Douglass Japan"]
};
