const all=window.LIGHTERS;
let tier='全部',view='db';
let aiFiles=[],aiLastResult=null;
const q=document.querySelector('#q'),results=document.querySelector('#results'),status=document.querySelector('#status'),filters=document.querySelector('#filters'),modal=document.querySelector('#modal'),detail=document.querySelector('#detail');
document.querySelector('#count').textContent=all.length;
const tiers=['全部',...new Set(all.map(x=>x.tier))];
const getJSON=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}},setJSON=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const DEFAULT_LINKS=[
  {name:'Lighter Library 全球製造商索引',url:'https://www.lighterlibrary.com/manufacturerindex.php',note:'全球 maker / manufacturer 索引'},
  {name:'Vintage Cigarette Lighters 收藏資料庫',url:'https://www.toledo-bend.us/VCL/lighters/',note:'老打火機、型錄、專利與機構資料'},
  {name:'VintageLighter 品牌索引',url:'https://www.vintagelighter.com/vintage-lighter-brands/',note:'大量 Vintage lighter 品牌名稱索引'},
  {name:'OTLS — On The Lighter Side',url:'https://otls.com/',note:'國際打火機收藏俱樂部'},
  {name:'Reddit r/lighters',url:'https://www.reddit.com/r/lighters/',note:'收藏者交流、辨識與展示'}
];
const SOURCE_OPTIONS=['Flea market / 跳蚤市場','蝦皮','露天','eBay','Etsy','Amazon','Yahoo拍賣','日本 Yahoo! Auctions','Mercari','Buyee / 代購','Carousell / 旋轉拍賣','官方網站','實體古董店','二手店','收藏店','拍賣會','朋友 / 私人交易','Facebook / 收藏社團','其他'];
const CURRENCY_OPTIONS=['TWD','USD','JPY','EUR','GBP','CNY','KRW','HKD','AUD','其他'];
const CONDITION_OPTIONS=['未評估','全新 / NOS','近全新','極佳','良好','普通','待整理 / 維修','零件品'];
const BRAND_GUIDES=window.LIGHTER_GUIDES||[];
function brandNotes(){return getJSON('lighterBrandNotes',{})}
function guideFor(name){return BRAND_GUIDES.find(g=>(g.match||[]).some(k=>norm(name).includes(norm(k))))||null}
function googleUrl(query){return 'https://www.google.com/search?q='+encodeURIComponent(query)}
function searchLink(label,query,cls='search-action'){return `<a class="${cls}" href="${esc(googleUrl(query))}" target="_blank" rel="noopener">${esc(label)} ↗</a>`}
function brandGuideHTML(x){
  const g=guideFor(x.name),notes=brandNotes()[x.name]||'';
  const dating=g?.dating?.length?`<div class="guide-block"><b>📅 年份 / 世代辨識</b><ul>${g.dating.map(v=>`<li>${esc(v)}</li>`).join('')}</ul></div>`:`<div class="guide-placeholder">這個品牌目前還沒有人工校對過的年份指南。先用下面的搜尋按鈕查資料，避免 App 自動亂猜年代。</div>`;
  const auth=g?.authenticity?.length?`<div class="guide-block"><b>✅ 真偽 / 原裝辨識</b><ul>${g.authenticity.map(v=>`<li>${esc(v)}</li>`).join('')}</ul></div>`:'';
  const sources=g?.sources?.length?`<div class="guide-sources"><b>資料來源</b>${g.sources.map(a=>`<a href="${esc(a.url)}" target="_blank" rel="noopener">${esc(a.name)} ↗</a>`).join('')}</div>`:'';
  return `<section class="guide-card"><div class="guide-title"><span>🔎</span><div><h3>${esc(g?.title||x.name+' 辨識 / 年份研究')}</h3><small>品牌頁面的辨識資料是研究輔助，不取代實物鑑定。</small></div></div>${dating}${auth}<div class="guide-actions">${searchLink('Google 型號介紹',`${x.name} lighter models catalog identification`)}${searchLink('Google 年份辨識',`${x.name} vintage lighter dating date identification`)}${searchLink('Google 真偽辨識',`${x.name} lighter authentic fake identification`)}${searchLink('搜尋收藏資料庫',`${x.name} lighter site:toledo-bend.us OR site:lighterlibrary.com`)}</div>${sources}<details class="personal-guide"><summary>📝 我的品牌辨識筆記</summary><textarea id="brandGuideNote" placeholder="例如：底印版本、年份規則、容易遇到的仿品特徵…">${esc(notes)}</textarea><button type="button" id="saveBrandGuideNote">儲存品牌筆記</button></details></section>`
}
function saved(){return getJSON('lighterSaved',[])}
function models(){return getJSON('lighterModels',{})}
function links(){return getJSON('lighterLinks',DEFAULT_LINKS)}
function norm(s){return(s||'').toLowerCase().normalize('NFKD')}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function safeUrl(s){try{const u=new URL(s);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}}
function uid(){return crypto.randomUUID?crypto.randomUUID():'m-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2)}
function normalizeModel(m){return {
  id:m.id||uid(),model:m.model||'',url:m.url||'',owned:!!m.owned,favorite:!!m.favorite,added:m.added||new Date().toISOString(),
  estimatedDate:m.estimatedDate||'',mechanism:m.mechanism||'',authenticity:m.authenticity||'',researchNotes:m.researchNotes||'',
  purchaseYear:m.purchaseYear||'',purchaseDate:m.purchaseDate||'',price:m.price??'',currency:m.currency||'TWD',source:m.source||'',sourceOther:m.sourceOther||'',seller:m.seller||'',purchaseLocation:m.purchaseLocation||'',condition:m.condition||'未評估',serial:m.serial||'',notes:m.notes??m.note??''
}}
function ensureModelIds(){let db=models(),changed=false;Object.keys(db).forEach(k=>{db[k]=db[k].map(m=>{const n=normalizeModel(m);if(JSON.stringify(n)!==JSON.stringify(m))changed=true;return n})});if(changed)setJSON('lighterModels',db)}
ensureModelIds();

// Photos are kept locally in IndexedDB, not in the public GitHub repository.
const PHOTO_DB='lighterDBPhotos',PHOTO_STORE='photos';
function openPhotoDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(PHOTO_DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(PHOTO_STORE))r.result.createObjectStore(PHOTO_STORE,{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function getPhotos(id){const db=await openPhotoDB();return new Promise((resolve,reject)=>{const tx=db.transaction(PHOTO_STORE,'readonly'),r=tx.objectStore(PHOTO_STORE).get(id);r.onsuccess=()=>resolve(r.result?.photos||[]);r.onerror=()=>reject(r.error)})}
async function putPhotos(id,photos){const db=await openPhotoDB();return new Promise((resolve,reject)=>{const tx=db.transaction(PHOTO_STORE,'readwrite');tx.objectStore(PHOTO_STORE).put({id,photos});tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function deletePhotos(id){const db=await openPhotoDB();return new Promise((resolve,reject)=>{const tx=db.transaction(PHOTO_STORE,'readwrite');tx.objectStore(PHOTO_STORE).delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
function blobToDataURL(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(blob)})}
function dataURLToBlob(dataURL){const [meta,b64]=dataURL.split(','),type=(meta.match(/data:(.*?);/)||[])[1]||'image/jpeg',bin=atob(b64),arr=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)arr[i]=bin.charCodeAt(i);return new Blob([arr],{type})}
async function compressImage(file){
  if(!file.type.startsWith('image/'))throw new Error('不是圖片檔');
  const bmp=await createImageBitmap(file),max=1600,scale=Math.min(1,max/Math.max(bmp.width,bmp.height)),w=Math.max(1,Math.round(bmp.width*scale)),h=Math.max(1,Math.round(bmp.height*scale));
  const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.drawImage(bmp,0,0,w,h);bmp.close?.();
  return new Promise(resolve=>c.toBlob(b=>resolve(b||file),'image/jpeg',0.84));
}

function renderFilters(){filters.innerHTML=tiers.map(t=>`<button class="chip ${tier===t?'on':''}" data-tier="${esc(t)}">${esc(t)}</button>`).join('');filters.querySelectorAll('button').forEach(b=>b.onclick=()=>{tier=b.dataset.tier;renderFilters();render()})}
function card(x){let on=saved().includes(x.name),arr=models()[x.name]||[],n=arr.length,c=arr.filter(m=>m.owned).length;return `<article class="card brandcard" data-brand="${esc(x.name)}"><div class="top"><div class="tier">${esc(x.tier)}</div><div class="name">${esc(x.name)}<div class="region">🌍 ${esc(x.region)}</div></div><button class="star ${on?'saved':''}" data-star="${esc(x.name)}">★</button></div><div class="type">分類：${esc(x.type)}</div><div class="note">${esc(x.note)}</div><div class="modelstat">型號 ${n} 筆${n?` · 已收藏 ${c}`:''}　› 點開管理</div></article>`}
function bindCards(){results.querySelectorAll('.brandcard').forEach(c=>c.onclick=e=>{if(e.target.closest('.star'))return;openBrand(c.dataset.brand)});results.querySelectorAll('.star').forEach(b=>b.onclick=e=>{e.stopPropagation();let s=saved(),n=b.dataset.star;s=s.includes(n)?s.filter(x=>x!==n):[...s,n];setJSON('lighterSaved',s);render()})}
function selectOptions(arr,value,empty='請選擇'){return `<option value="">${empty}</option>`+arr.map(x=>`<option value="${esc(x)}" ${x===value?'selected':''}>${esc(x)}</option>`).join('')}
function modelFormHTML(name,m=null,index=null){const x=m?normalizeModel(m):normalizeModel({});const editing=index!==null;return `<form id="modelForm" class="form model-form" data-id="${esc(x.id)}">
  <div class="field full"><label>型號名稱 *</label><div class="input-with-action"><input name="model" required value="${esc(x.model)}" placeholder="例如 Standard / Single Claw"><button type="button" id="googleModelBtn" class="inline-search">Google 搜尋</button></div><small class="field-hint">輸入型號後可直接搜尋「品牌＋型號＋介紹」。</small></div>
  <div class="field full"><label>看到這個型號的網頁</label><input name="url" type="url" value="${esc(x.url)}" placeholder="https://…"></div>
  <label class="favorite-toggle ${x.favorite?'is-favorite':''}"><input id="favoriteInput" name="favorite" type="checkbox" ${x.favorite?'checked':''}><span class="favorite-heart">♥</span><span><b>加入我的最愛</b><small>適合先記下想找、想買或值得追蹤的型號</small></span></label>
  <div class="field"><label>推測年代 / 年份</label><input name="estimatedDate" value="${esc(x.estimatedDate)}" placeholder="例如 1930s / 1950–1955"></div>
  <div class="field"><label>機構 / 類型</label><input name="mechanism" value="${esc(x.mechanism)}" placeholder="例如 Semi-Automatic / Petrol"></div>
  <div class="field full"><label>AI / 研究筆記</label><textarea name="researchNotes" placeholder="年份辨識、真偽疑點、刻字、AI 初判等研究資訊">${esc(x.researchNotes)}</textarea></div>
  <label class="owned-toggle ${x.owned?'is-owned':''}"><input id="ownedInput" name="owned" type="checkbox" ${x.owned?'checked':''}><span class="owned-box">✓</span><span><b>我已收藏這個型號</b><small>勾選後可填購買資料與上傳收藏照片</small></span></label>
  <section id="collectionFields" class="collection-fields ${x.owned?'':'hidden-fields'}">
    <div class="collection-title">📦 收藏資料</div>
    <div class="field"><label>購買年分</label><input name="purchaseYear" type="number" min="1800" max="2100" inputmode="numeric" value="${esc(x.purchaseYear)}" placeholder="例如 2026"></div>
    <div class="field"><label>購買日期</label><input name="purchaseDate" type="date" value="${esc(x.purchaseDate)}"></div>
    <div class="field"><label>價錢</label><input name="price" type="number" min="0" step="0.01" inputmode="decimal" value="${esc(x.price)}" placeholder="例如 1800"></div>
    <div class="field"><label>幣別</label><select name="currency">${selectOptions(CURRENCY_OPTIONS,x.currency,'請選擇幣別')}</select></div>
    <div class="field full"><label>來源</label><select id="sourceSelect" name="source">${selectOptions(SOURCE_OPTIONS,x.source,'請選擇購買來源')}</select></div>
    <div id="sourceOtherWrap" class="field full ${x.source==='其他'?'':'conditional-hidden'}"><label>其他來源</label><input name="sourceOther" value="${esc(x.sourceOther)}" placeholder="請輸入來源"></div>
    <div class="field"><label>賣家 / 店家</label><input name="seller" value="${esc(x.seller)}" placeholder="可留空"></div>
    <div class="field"><label>購買地點 / 國家</label><input name="purchaseLocation" value="${esc(x.purchaseLocation)}" placeholder="例如 日本大阪"></div>
    <div class="field"><label>品相</label><select name="condition">${selectOptions(CONDITION_OPTIONS,x.condition,'請選擇品相')}</select></div>
    <div class="field"><label>序號 / 刻字</label><input name="serial" value="${esc(x.serial)}" placeholder="底部刻字、序號等"></div>
    <div class="field full"><label>收藏備註</label><textarea name="notes" placeholder="只放其他補充，不用再把價格、來源塞在這裡">${esc(x.notes)}</textarea></div>
    <div class="field full photo-field"><label>收藏照片 <small>最多 5 張，會存在你的手機 / 瀏覽器</small></label><input id="photoInput" name="photos" type="file" accept="image/*" multiple><div id="photoPreview" class="photo-preview"></div>${editing?'<label class="remove-photo"><input id="removePhotos" type="checkbox"> 刪除這個型號目前所有照片</label>':''}</div>
  </section>
  <div class="form-actions"><button type="submit">${editing?'儲存修改':'＋ 新增型號'}</button>${editing?'<button type="button" id="cancelEdit" class="secondary">取消編輯</button>':''}</div>
</form>`}
function openBrand(name,editIndex=null,prefill=null){const x=all.find(a=>a.name===name);if(!x)return;const arr=models()[name]||[],editing=editIndex!==null?arr[editIndex]:null,formData=editing||(prefill?normalizeModel(prefill):null);detail.innerHTML=`<div class="detailhead"><div class="tier">${esc(x.tier)}</div><div><h2>${esc(x.name)}</h2><div class="region">🌍 ${esc(x.region)} · ${esc(x.type)}</div></div></div><p class="detailnote">${esc(x.note)}</p>${brandGuideHTML(x)}<h3>${editing?'編輯型號':'新增 / 管理型號'}</h3>${modelFormHTML(name,formData,editIndex)}<h3>已收錄型號</h3><div id="modelList">${arr.length?arr.map((m,i)=>modelRow(m,i,name)).join(''):'<div class="empty small">目前還沒有型號，看到喜歡的就加進來。</div>'}</div>`;
  modal.classList.remove('hidden');document.body.classList.add('lock');bindBrandGuide(name);bindModelForm(name,editIndex);bindModelActions(name);loadAllModelPhotos(name);if(editing)loadEditPhotos(editing.id)}
function bindBrandGuide(name){const saveBtn=detail.querySelector('#saveBrandGuideNote'),ta=detail.querySelector('#brandGuideNote');if(saveBtn&&ta)saveBtn.onclick=()=>{const d=brandNotes();d[name]=ta.value;setJSON('lighterBrandNotes',d);saveBtn.textContent='✓ 已儲存';setTimeout(()=>saveBtn.textContent='儲存品牌筆記',1200)}}
function bindModelForm(name,editIndex){const form=document.querySelector('#modelForm'),owned=form.querySelector('#ownedInput'),fields=form.querySelector('#collectionFields'),toggle=form.querySelector('.owned-toggle'),source=form.querySelector('#sourceSelect'),sourceOther=form.querySelector('#sourceOtherWrap'),date=form.elements.purchaseDate,year=form.elements.purchaseYear,photoInput=form.querySelector('#photoInput'),googleBtn=form.querySelector('#googleModelBtn');
  // Some mobile browsers/PWA caches previously left an invisible layer over the form. Force real form controls to receive focus/clicks.
  form.querySelectorAll('input,textarea,select,button').forEach(el=>{el.style.pointerEvents='auto'});
  googleBtn.onclick=()=>{const model=form.elements.model.value.trim(),query=model?`${name} ${model} lighter introduction identification`:`${name} lighter models catalog`;window.open(googleUrl(query),'_blank','noopener')};
  const refreshOwned=()=>{fields.classList.toggle('hidden-fields',!owned.checked);toggle.classList.toggle('is-owned',owned.checked)};owned.onchange=refreshOwned;refreshOwned();
  source.onchange=()=>sourceOther.classList.toggle('conditional-hidden',source.value!=='其他');
  date.onchange=()=>{if(date.value&&!year.value)year.value=date.value.slice(0,4)};
  photoInput.onchange=()=>previewSelectedPhotos(photoInput.files);
  if(editIndex!==null)form.querySelector('#cancelEdit').onclick=()=>openBrand(name);
  form.onsubmit=async e=>{e.preventDefault();const fd=new FormData(form),db=models(),arr=db[name]||[],existing=editIndex!==null?normalizeModel(arr[editIndex]):null,id=existing?.id||form.dataset.id||uid(),ownedNow=fd.get('owned')==='on';
    const rec=normalizeModel({...(existing||{}),id,model:fd.get('model').trim(),url:fd.get('url').trim(),favorite:fd.get('favorite')==='on',estimatedDate:fd.get('estimatedDate').trim(),mechanism:fd.get('mechanism').trim(),researchNotes:fd.get('researchNotes').trim(),owned:ownedNow,purchaseYear:ownedNow?fd.get('purchaseYear').trim():'',purchaseDate:ownedNow?fd.get('purchaseDate').trim():'',price:ownedNow?fd.get('price').trim():'',currency:ownedNow?fd.get('currency'):'TWD',source:ownedNow?fd.get('source'):'',sourceOther:ownedNow?fd.get('sourceOther').trim():'',seller:ownedNow?fd.get('seller').trim():'',purchaseLocation:ownedNow?fd.get('purchaseLocation').trim():'',condition:ownedNow?fd.get('condition'):'未評估',serial:ownedNow?fd.get('serial').trim():'',notes:ownedNow?fd.get('notes').trim():''});
    if(editIndex!==null)arr[editIndex]=rec;else arr.push(rec);db[name]=arr;setJSON('lighterModels',db);
    try{let current=await getPhotos(id);if(form.querySelector('#removePhotos')?.checked)current=[];const files=[...photoInput.files].slice(0,5);if(ownedNow&&files.length){const room=Math.max(0,5-current.length),fresh=[];for(const f of files.slice(0,room))fresh.push(await compressImage(f));current=[...current,...fresh]}if(current.length)await putPhotos(id,current);else await deletePhotos(id)}catch(err){console.error(err);alert('型號已儲存，但照片處理失敗。可以稍後再編輯上傳。')}
    openBrand(name);render();
  }
}
async function previewSelectedPhotos(files){const p=document.querySelector('#photoPreview');if(!p)return;p.innerHTML='';for(const f of [...files].slice(0,5)){const url=URL.createObjectURL(f),img=document.createElement('img');img.src=url;img.onload=()=>URL.revokeObjectURL(url);p.appendChild(img)}}
async function loadEditPhotos(id){const p=document.querySelector('#photoPreview');if(!p)return;try{const ps=await getPhotos(id);for(const blob of ps){const url=URL.createObjectURL(blob),img=document.createElement('img');img.src=url;img.onload=()=>URL.revokeObjectURL(url);p.appendChild(img)}}catch{}}
function formatPrice(m){if(m.price===''||m.price==null)return'';const n=Number(m.price),v=Number.isFinite(n)?n.toLocaleString():m.price;return `${m.currency||''} ${v}`.trim()}
function sourceLabel(m){return m.source==='其他'?(m.sourceOther||'其他'):m.source}
function dataLine(label,value){return value?`<div class="data-line"><span>${esc(label)}</span><b>${esc(value)}</b></div>`:''}
function modelRow(m,i,name){m=normalizeModel(m);const u=safeUrl(m.url);return `<div class="modelrow ${m.owned?'owned-row':''} ${m.favorite?'favorite-row':''}" data-model-id="${esc(m.id)}"><div class="modeltop"><div class="model-badges"><label class="owned-pill ${m.owned?'on':''}"><input type="checkbox" data-own="${i}" ${m.owned?'checked':''}><span class="box">✓</span><b>${m.owned?'已收藏':'未收藏'}</b></label><button type="button" class="model-fav ${m.favorite?'on':''}" data-model-fav="${i}" title="我的最愛">♥</button></div><div class="row-actions"><button type="button" class="edit" data-model-edit="${i}">編輯</button><button type="button" class="danger" data-del="${i}">刪除</button></div></div><div class="modelname">${esc(m.model)}</div>${m.estimatedDate||m.mechanism||m.authenticity?`<div class="research-chips">${m.estimatedDate?`<span>📅 ${esc(m.estimatedDate)}</span>`:''}${m.mechanism?`<span>⚙ ${esc(m.mechanism)}</span>`:''}${m.authenticity?`<span>🔎 ${esc(m.authenticity)}</span>`:''}</div>`:''}${m.researchNotes?`<div class="research-note"><span>AI / 研究筆記</span><p>${esc(m.researchNotes)}</p></div>`:''}${m.owned?`<div class="collection-data">${dataLine('購買年分',m.purchaseYear)}${dataLine('購買日期',m.purchaseDate)}${dataLine('價錢',formatPrice(m))}${dataLine('來源',sourceLabel(m))}${dataLine('賣家 / 店家',m.seller)}${dataLine('購買地點 / 國家',m.purchaseLocation)}${dataLine('品相',m.condition&&m.condition!=='未評估'?m.condition:'')}${dataLine('序號 / 刻字',m.serial)}${m.notes?`<div class="data-note"><span>收藏備註</span><p>${esc(m.notes)}</p></div>`:''}</div><div class="photo-gallery" data-photo-id="${esc(m.id)}"></div>`:''}${u?`<a class="source" href="${esc(u)}" target="_blank" rel="noopener">開啟型號來源網頁 ↗</a>`:''}</div>`}
async function loadAllModelPhotos(name){const arr=models()[name]||[];for(const m0 of arr){const m=normalizeModel(m0);if(!m.owned)continue;const box=detail.querySelector(`[data-photo-id="${CSS.escape(m.id)}"]`);if(!box)continue;try{const ps=await getPhotos(m.id);for(const blob of ps){const url=URL.createObjectURL(blob),img=document.createElement('img');img.src=url;img.alt=m.model;img.onclick=()=>window.open(url,'_blank');box.appendChild(img)}}catch{}}}
function bindModelActions(name){detail.querySelectorAll('[data-own]').forEach(el=>el.onchange=()=>{let db=models();const i=+el.dataset.own;db[name][i]=normalizeModel(db[name][i]);db[name][i].owned=el.checked;setJSON('lighterModels',db);openBrand(name);render()});detail.querySelectorAll('[data-model-fav]').forEach(el=>el.onclick=()=>{let db=models();const i=+el.dataset.modelFav;db[name][i]=normalizeModel(db[name][i]);db[name][i].favorite=!db[name][i].favorite;setJSON('lighterModels',db);openBrand(name);render()});detail.querySelectorAll('[data-model-edit]').forEach(el=>el.onclick=e=>{e.stopPropagation();openBrand(name,+el.dataset.modelEdit)});detail.querySelectorAll('[data-del]').forEach(el=>el.onclick=async()=>{if(!confirm('確定刪除這筆型號？'))return;let db=models(),m=normalizeModel(db[name][+el.dataset.del]);db[name].splice(+el.dataset.del,1);setJSON('lighterModels',db);await deletePhotos(m.id).catch(()=>{});openBrand(name);render()})}

function aiEndpoint(){return (localStorage.getItem('lighterAIEndpoint')||'').trim().replace(/\/+$/,'')}
function setAIEndpoint(v){const clean=(v||'').trim().replace(/\/+$/,'');if(clean)localStorage.setItem('lighterAIEndpoint',clean);else localStorage.removeItem('lighterAIEndpoint');return clean}
function findBrandMatch(name){const n=norm(name);if(!n||n==='未知')return null;let exact=all.find(x=>norm(x.name)===n);if(exact)return exact;let contain=all.find(x=>norm(x.name).includes(n)||n.includes(norm(x.name)));if(contain)return contain;const toks=n.split(/[^a-z0-9]+/).filter(x=>x.length>=4);let best=null,score=0;for(const x of all){const xn=norm(x.name),s=toks.filter(t=>xn.includes(t)).length;if(s>score){best=x;score=s}}return score?best:null}
function aiList(title,arr){return Array.isArray(arr)&&arr.length?`<div class="ai-block"><b>${esc(title)}</b><ul>${arr.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}
function estimateAICost(data){const u=data?.usage||{},input=Number(u.input_tokens||0),output=Number(u.output_tokens||0),model=data?.model||'';let inRate=0,outRate=0;if(model.includes('luna')){inRate=.20;outRate=1.20}else if(model.includes('sol')){inRate=4;outRate=20}else return null;const cost=input/1e6*inRate+output/1e6*outRate;return {cost,input,output}}
function recordAICost(data){const e=estimateAICost(data);if(!e)return;const log=getJSON('lighterAICostLog',[]);log.push({date:new Date().toISOString(),model:data.model,cost:e.cost,input:e.input,output:e.output});setJSON('lighterAICostLog',log.slice(-1000))}
function monthAICost(){const ym=new Date().toISOString().slice(0,7);return getJSON('lighterAICostLog',[]).filter(x=>(x.date||'').startsWith(ym)).reduce((n,x)=>n+Number(x.cost||0),0)}
function aiCostHTML(data){const e=estimateAICost(data);if(!e)return '';return `<div class="ai-cost"><b>API 用量估算</b><span>本次約 US$${e.cost.toFixed(e.cost<0.01?4:3)} · Input ${e.input.toLocaleString()} / Output ${e.output.toLocaleString()} tokens</span><small>本月此裝置累積約 US$${monthAICost().toFixed(3)}。僅估算模型 token 費，不含 Web Search 等工具費；官方價格可能調整。</small></div>`}
function aiResearchNotes(a){const lines=[];if(a.summary)lines.push('AI 摘要：'+a.summary);if(a.authenticity)lines.push('真偽 / 原裝初判：'+a.authenticity+(a.authenticity_reason?' — '+a.authenticity_reason:''));if(Array.isArray(a.visible_markings)&&a.visible_markings.length)lines.push('可見刻字：'+a.visible_markings.join('；'));if(Array.isArray(a.concerns)&&a.concerns.length)lines.push('疑點：'+a.concerns.join('；'));return lines.join('\n')}
async function saveAIToDB(data,{owned=false,favorite=false}={}){const a=data?.analysis||{},match=findBrandMatch(a.brand);if(!match)throw new Error('資料庫找不到對應品牌');let db=models(),arr=db[match.name]||[],src=(data.sources||[]).find(s=>safeUrl(s.url)),rec=normalizeModel({model:a.model&&a.model!=='未知'?a.model:'AI 未確定型號',url:src?.url||'',owned,favorite,estimatedDate:a.date_range&&a.date_range!=='未知'?a.date_range:'',mechanism:a.mechanism&&a.mechanism!=='未知'?a.mechanism:'',authenticity:a.authenticity||'',researchNotes:aiResearchNotes(a)});arr.push(rec);db[match.name]=arr;setJSON('lighterModels',db);if(owned&&aiFiles.length){const ps=[];for(const f of aiFiles.slice(0,5))ps.push(await compressImage(f));if(ps.length)await putPhotos(rec.id,ps)}return {brand:match.name,index:arr.length-1,rec}}
function aiResultHTML(data){const a=data?.analysis||{},match=findBrandMatch(a.brand),sources=Array.isArray(data?.sources)?data.sources:[],authClass=a.authenticity==='較符合真品特徵'?'good':a.authenticity==='有疑點'?'warn':'neutral';return `<section class="ai-result"><div class="ai-result-head"><div><small>AI 照片初判</small><h2>${esc(a.brand||'未知')} ${a.model&&a.model!=='未知'?`<span>${esc(a.model)}</span>`:''}</h2></div><div class="confidence">把握：${esc(a.confidence||'—')}</div></div><div class="ai-facts"><div><span>推測年代</span><b>${esc(a.date_range||'未知')}</b></div><div><span>國家</span><b>${esc(a.country||'未知')}</b></div><div><span>機構</span><b>${esc(a.mechanism||'未知')}</b></div><div><span>分析模型</span><b>${esc(data.model||'—')}</b></div></div>${aiCostHTML(data)}<div class="auth-box ${authClass}"><span>真偽 / 原裝初判</span><strong>${esc(a.authenticity||'無法判定')}</strong><p>${esc(a.authenticity_reason||'')}</p></div>${a.summary?`<div class="ai-summary">${esc(a.summary)}</div>`:''}${aiList('看得到的刻字 / 標記',a.visible_markings)}${aiList('支持判斷的特徵',a.evidence)}${aiList('疑點 / 需要注意',a.concerns)}${aiList('建議補拍',a.missing_photos)}${sources.length?`<div class="ai-sources"><b>網路查證來源</b>${sources.map(s=>`<a href="${esc(safeUrl(s.url))}" target="_blank" rel="noopener">${esc(s.title||s.url)} ↗</a>`).join('')}</div>`:''}<div class="ai-actions">${match?`<button id="aiSaveModel">＋ 存成型號資料</button><button id="aiFavoriteModel" class="secondary">♥ 加入我的最愛</button><button id="aiAddOwned" class="secondary">✓ 加入我的收藏</button>`:`<button type="button" disabled>資料庫目前找不到對應品牌</button>`}<button type="button" id="aiGoogleResult" class="secondary">Google 再查一次</button></div><p class="ai-disclaimer">AI 只能根據照片與可查到的資料做初判；高價、稀有或疑似重製品仍建議比對實物、專利、型錄與可靠收藏資料。</p></section>`}
function renderAIFilePreview(){const box=document.querySelector('#aiPhotoPreview');if(!box)return;box.innerHTML=aiFiles.map((f,i)=>`<div class="ai-photo"><img data-ai-preview="${i}" alt="待辨識照片"><button type="button" data-ai-remove="${i}">×</button></div>`).join('');box.querySelectorAll('[data-ai-preview]').forEach(img=>{const f=aiFiles[+img.dataset.aiPreview],u=URL.createObjectURL(f);img.src=u;img.onload=()=>URL.revokeObjectURL(u)});box.querySelectorAll('[data-ai-remove]').forEach(b=>b.onclick=()=>{aiFiles.splice(+b.dataset.aiRemove,1);renderAIFilePreview();updateAIPhotoCount()});updateAIPhotoCount()}
function updateAIPhotoCount(){const el=document.querySelector('#aiPhotoCount');if(el)el.textContent=`${aiFiles.length} / 6 張`}
function addAIFiles(files){for(const f of files){if(!f.type.startsWith('image/'))continue;if(aiFiles.length>=6)break;aiFiles.push(f)}renderAIFilePreview()}
async function aiImageDataURLs(){const out=[];for(const f of aiFiles.slice(0,6)){const blob=await compressImage(f);out.push(await blobToDataURL(blob))}return out}
async function testAIConnection(){const endpoint=aiEndpoint(),box=document.querySelector('#aiConnectionStatus');if(!endpoint){box.textContent='請先輸入 Worker 網址。';box.className='connection bad';return}box.textContent='測試連線中…';box.className='connection';try{const r=await fetch(endpoint+'/health',{cache:'no-store'}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'連線失敗');box.textContent='✓ AI 後端連線正常';box.className='connection good'}catch(e){box.textContent='✕ '+(e.message||'無法連線');box.className='connection bad'}}
function bindAIResult(data){const a=data?.analysis||{},match=findBrandMatch(a.brand);document.querySelector('#aiGoogleResult')?.addEventListener('click',()=>window.open(googleUrl(`${a.brand||''} ${a.model||''} lighter identification authenticity dating`),'_blank','noopener'));const act=async(id,opts,msg)=>{const b=document.querySelector(id);if(!b||!match)return;b.addEventListener('click',async()=>{const old=b.textContent;b.disabled=true;b.textContent='儲存中…';try{const r=await saveAIToDB(data,opts);b.textContent='✓ '+msg;render();setTimeout(()=>{if(document.body.contains(b)){b.disabled=false;b.textContent=old}},1200);if(opts.owned)openBrand(r.brand,r.index)}catch(e){alert(e.message||String(e));b.disabled=false;b.textContent=old}})};act('#aiSaveModel',{owned:false,favorite:false},'已存型號');act('#aiFavoriteModel',{owned:false,favorite:true},'已加入最愛');act('#aiAddOwned',{owned:true,favorite:false},'已加入收藏')}
async function runAIAnalysis(){const endpoint=aiEndpoint(),btn=document.querySelector('#aiAnalyze'),out=document.querySelector('#aiOutput'),mode=document.querySelector('#aiMode')?.value||'quick',hint=document.querySelector('#aiHint')?.value||'';if(!endpoint){alert('請先在 AI 設定填入 Cloudflare Worker 網址。');return}if(!aiFiles.length){alert('請先拍照或選擇至少一張照片。');return}const old=btn.textContent;btn.disabled=true;btn.textContent=mode==='deep'?'正在深入查證…':'正在辨識照片…';out.innerHTML='<div class="ai-loading"><div class="spinner"></div><b>AI 正在看照片</b><span>辨識底印、機構與刻字，請稍候。</span></div>';try{const images=await aiImageDataURLs(),r=await fetch(endpoint+'/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({images,mode,hint,catalog:all.map(x=>x.name)})}),d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||`HTTP ${r.status}`);aiLastResult=d;recordAICost(d);out.innerHTML=aiResultHTML(d);bindAIResult(d)}catch(e){console.error(e);out.innerHTML=`<div class="ai-error"><b>辨識失敗</b><p>${esc(e.message||String(e))}</p><small>如果是 401 / quota / billing 錯誤，通常要回 OpenAI Platform 檢查 API key 或 API 餘額。</small></div>`}finally{btn.disabled=false;btn.textContent=old}}
function renderAI(){const endpoint=aiEndpoint();results.innerHTML=`<section class="ai-page"><div class="ai-hero"><div class="ai-icon">✦</div><div><h2>AI 打火機辨識</h2><p>拍攝正面、底印、鉸鏈與點火機構，AI 會嘗試辨識品牌、型號、年代並做真偽 / 原裝風險初判。</p></div></div><details class="ai-config" ${endpoint?'':'open'}><summary>⚙ AI 後端設定 ${endpoint?'<span class="setup-ok">已設定</span>':'<span class="setup-needed">尚未設定</span>'}</summary><div class="field"><label>Cloudflare Worker 網址</label><input id="aiEndpointInput" type="url" value="${esc(endpoint)}" placeholder="https://lighter-db-ai.xxxxx.workers.dev"><small>这里只存 Worker 網址，不是 OpenAI API key。API key 絕對不要放進這個 App 或 GitHub。</small></div><div class="config-actions"><button id="saveAIEndpoint">儲存網址</button><button id="testAIEndpoint" class="secondary">測試連線</button></div><div id="aiConnectionStatus" class="connection"></div></details><div class="ai-capture card"><h3>① 拍攝 / 選擇照片</h3><p class="fineprint">最多 6 張。最好包含：全貌、底部刻字、Logo、鉸鏈、火輪 / 點火機構、加油口或內膽。</p><div class="capture-buttons"><label class="capture-btn">📷 直接拍照<input id="aiCamera" type="file" accept="image/*" capture="environment"></label><label class="capture-btn secondary">▣ 從相簿選擇<input id="aiAlbum" type="file" accept="image/*" multiple></label></div><div class="ai-photo-meta"><span id="aiPhotoCount">0 / 6 張</span><button type="button" id="aiClearPhotos">清除全部</button></div><div id="aiPhotoPreview" class="ai-photo-preview"></div></div><div class="ai-options card"><h3>② 分析設定</h3><div class="field"><label>你已知的線索（選填）</label><textarea id="aiHint" placeholder="例如：賣家說是 Thorens、底部看到 PAT. 1912、疑似重新鍍鉻…"></textarea></div><div class="field"><label>分析模式</label><select id="aiMode"><option value="quick">快速辨識 — GPT-5.6 Luna（較省）</option><option value="deep">深入鑑定 — GPT-5.6 Sol + 網路查證</option></select></div><button id="aiAnalyze" class="ai-analyze">✦ 開始 AI 辨識</button></div><div id="aiOutput">${aiLastResult?aiResultHTML(aiLastResult):'<div class="ai-empty"><b>還沒有辨識結果</b><span>先拍幾張打火機照片，再按「開始 AI 辨識」。</span></div>'}</div></section>`;document.querySelector('#saveAIEndpoint').onclick=()=>{const v=setAIEndpoint(document.querySelector('#aiEndpointInput').value);document.querySelector('#aiEndpointInput').value=v;testAIConnection()};document.querySelector('#testAIEndpoint').onclick=testAIConnection;document.querySelector('#aiCamera').onchange=e=>{addAIFiles([...e.target.files]);e.target.value=''};document.querySelector('#aiAlbum').onchange=e=>{addAIFiles([...e.target.files]);e.target.value=''};document.querySelector('#aiClearPhotos').onclick=()=>{aiFiles=[];renderAIFilePreview()};document.querySelector('#aiAnalyze').onclick=runAIAnalysis;renderAIFilePreview();if(aiLastResult)bindAIResult(aiLastResult)}

function favoriteModels(){const out=[];const db=models();for(const [brand,arr] of Object.entries(db))arr.forEach((m,i)=>{m=normalizeModel(m);if(m.favorite)out.push({brand,m,index:i})});return out}
function renderFavorites(){filters.style.display='none';q.parentElement.style.display='none';status.textContent='';const brands=all.filter(x=>saved().includes(x.name)),mods=favoriteModels();results.innerHTML=`<div class="favorites-page"><h2>♥ 我的最愛</h2><p>把想追蹤的品牌與型號集中在這裡；「最愛」不等於已收藏。</p><h3>最愛品牌 <span class="count-pill">${brands.length}</span></h3><div class="favorite-brand-grid">${brands.length?brands.map(card).join(''):'<div class="empty small">還沒有最愛品牌。到資料庫按品牌右側 ★。</div>'}</div><h3>最愛型號 <span class="count-pill">${mods.length}</span></h3><div class="favorite-models">${mods.length?mods.map(({brand,m,index})=>`<article class="favorite-model-card" data-fav-brand="${esc(brand)}" data-fav-index="${index}"><button class="fav-heart on" data-unfav-brand="${esc(brand)}" data-unfav-index="${index}">♥</button><small>${esc(brand)}</small><h3>${esc(m.model)}</h3>${m.estimatedDate?`<div>📅 ${esc(m.estimatedDate)}</div>`:''}${m.mechanism?`<div>⚙ ${esc(m.mechanism)}</div>`:''}${m.owned?'<span class="owned-tag">✓ 已收藏</span>':'<span class="watch-tag">想找 / 追蹤</span>'}</article>`).join(''):'<div class="empty small">還沒有最愛型號。品牌頁或 AI 辨識結果都可以按 ♥。</div>'}</div></div>`;bindCards();results.querySelectorAll('.favorite-model-card').forEach(c=>c.onclick=e=>{if(e.target.closest('[data-unfav-brand]'))return;openBrand(c.dataset.favBrand,+c.dataset.favIndex)});results.querySelectorAll('[data-unfav-brand]').forEach(b=>b.onclick=e=>{e.stopPropagation();const brand=b.dataset.unfavBrand,i=+b.dataset.unfavIndex,db=models();db[brand][i]=normalizeModel(db[brand][i]);db[brand][i].favorite=false;setJSON('lighterModels',db);renderFavorites()})}

function renderLinks(){let a=links();results.innerHTML=`<div class="about"><h2>參考資料</h2><p>把常用的收藏資料庫、論壇、文章或賣場放在這裡。</p><form id="linkForm" class="form"><div class="field"><label>網站名稱</label><input name="name" required placeholder="例如 Lighter Library"></div><div class="field"><label>網址</label><input name="url" type="url" required placeholder="https://…"></div><div class="field full"><label>用途 / 備註</label><input name="note" placeholder="例如：查製造商、專利、型錄"></div><button class="full">＋ 新增網址</button></form><div>${a.map((l,i)=>`<div class="linkrow"><div><b>${esc(l.name)}</b>${l.note?`<div class="note">${esc(l.note)}</div>`:''}<a class="source" href="${esc(safeUrl(l.url))}" target="_blank" rel="noopener">開啟網站 ↗</a></div><button class="danger" data-linkdel="${i}">刪除</button></div>`).join('')}</div></div>`;document.querySelector('#linkForm').onsubmit=e=>{e.preventDefault();let fd=new FormData(e.target),a=links();a.push({name:fd.get('name').trim(),url:fd.get('url').trim(),note:fd.get('note').trim()});setJSON('lighterLinks',a);render()};results.querySelectorAll('[data-linkdel]').forEach(b=>b.onclick=()=>{if(confirm('刪除這個網址？')){let a=links();a.splice(+b.dataset.linkdel,1);setJSON('lighterLinks',a);render()}})}
async function exportBackup(){const db=models(),photos={};for(const arr of Object.values(db)){for(const m0 of arr){const m=normalizeModel(m0);try{const ps=await getPhotos(m.id);if(ps.length)photos[m.id]=await Promise.all(ps.map(blobToDataURL))}catch{}}}const data={version:7,exported:new Date().toISOString(),saved:saved(),models:db,links:links(),brandNotes:brandNotes(),aiEndpoint:aiEndpoint(),aiCostLog:getJSON('lighterAICostLog',[]),photos},blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`lighter-db-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function importBackupFile(f){const text=await f.text(),d=JSON.parse(text);if(d.saved)setJSON('lighterSaved',d.saved);if(d.models)setJSON('lighterModels',d.models);if(d.links)setJSON('lighterLinks',d.links);if(d.brandNotes)setJSON('lighterBrandNotes',d.brandNotes);if(d.aiEndpoint)setAIEndpoint(d.aiEndpoint);if(d.aiCostLog)setJSON('lighterAICostLog',d.aiCostLog);ensureModelIds();if(d.photos){for(const [id,arr] of Object.entries(d.photos)){await putPhotos(id,arr.map(dataURLToBlob))}}}
function renderAbout(){results.innerHTML=`<div class="about"><h2>關於 Lighter DB</h2><p>內建 ${all.length} 筆品牌 / Maker。Tier 是 Vintage / antique lighter 收藏取向，不等於價格保證。</p><p><b>重要：</b>搜尋不到只代表目前資料庫未收錄，不代表它是雜牌。</p><h3>資料備份</h3><p>你新增的型號、收藏欄位、勾選、網址和照片都存在目前裝置的瀏覽器資料。建議偶爾匯出完整備份。</p><div class="backup"><button id="exportBtn">↓ 匯出完整備份（含照片）</button><label class="import">↑ 匯入備份<input id="importFile" type="file" accept="application/json"></label></div><p class="fineprint">照片會先壓縮再存到本機資料庫；備份包含照片時檔案會比較大。</p></div>`;document.querySelector('#exportBtn').onclick=async e=>{const b=e.currentTarget,old=b.textContent;b.disabled=true;b.textContent='正在整理備份…';try{await exportBackup()}finally{b.disabled=false;b.textContent=old}};document.querySelector('#importFile').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{await importBackupFile(f);alert('備份已匯入');render()}catch(err){console.error(err);alert('這不是有效的 Lighter DB 備份檔，或檔案已損壞。')}}}
function render(){if(view==='mine'){renderFavorites();return}if(view==='ai'||view==='links'||view==='about'){filters.style.display='none';q.parentElement.style.display='none';status.textContent='';if(view==='ai')renderAI();else if(view==='links')renderLinks();else renderAbout();return}filters.style.display='flex';q.parentElement.style.display='flex';let data=all;let term=norm(q.value.trim());if(term)data=data.filter(x=>norm([x.name,x.region,x.type,x.note].join(' ')).includes(term));if(tier!=='全部')data=data.filter(x=>x.tier===tier);status.textContent=`找到 ${data.length} 筆${term?' · 搜尋「'+q.value.trim()+'」':''}`;results.innerHTML=data.length?data.map(card).join(''):`<div class="empty"><b>${term?'目前資料庫沒有找到':'這裡目前是空的'}</b>${term?'這不代表它不是品牌。請保留名稱，之後再查證並加入資料庫。':'點品牌右側 ★ 就能加入品牌收藏。'}</div>`;bindCards()}
q.oninput=render;document.querySelector('#clear').onclick=()=>{q.value='';q.focus();render()};document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===b));render()});document.querySelector('#closeModal').onclick=()=>{modal.classList.add('hidden');document.body.classList.remove('lock')};modal.onclick=e=>{if(e.target===modal)document.querySelector('#closeModal').click()};renderFilters();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
