window.LIGHTER_LOGO_DOMAINS = {
  "Dunhill": "dunhill.com",
  "S.T. Dupont": "st-dupont.com",
  "Cartier": "cartier.com",
  "Zippo": "zippo.com",
  "BIC": "bic.com",
  "Clipper": "clipper.eu",
  "XIKAR": "xikar.com",
  "Sarome": "sarome.com",
  "Windmill": "windmill.co.jp",
  "Tsubota Pearl": "tsubotapearl.co.jp",
  "ZORRO": "zorro-lighter.com",
  "Colibri": "colibri.com",
  "Rowenta": "rowenta.com",
  "Braun": "braun.com",
  "Lancel": "lancel.com",
  "Asprey": "asprey.com",
  "Parker": "parkerpen.com",
  "Cricket": "cricketlighters.com",
  "Prometheus": "prometheuskkp.com",
  "Vector": "vectorkgm.com",
  "Sillems": "sillems.com"
};
