// v12.4 — curated logo / historical maker-mark expansion.
// Modern brands prefer official/current web identities; older makers use a
// recognizable period maker mark / wordmark where a clean standalone logo is scarce.
// User overrides in the app always take priority.
(function(){
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const data=svg=>'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(svg);
  const canvas=(inner)=>data(`<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 520 260'><rect width='520' height='260' rx='30' fill='#fff'/>${inner}</svg>`);
  const word=(t,opt={})=>canvas(`<text x='260' y='145' text-anchor='middle' font-family='${opt.font||"Arial,Helvetica,sans-serif"}' font-size='${opt.size||70}' font-weight='${opt.weight||800}' font-style='${opt.italic?"italic":"normal"}' letter-spacing='${opt.spacing||0}' fill='#111'>${esc(t)}</text>${opt.line?`<line x1='110' x2='410' y1='170' y2='170' stroke='#111' stroke-width='6'/>`:''}`);
  const script=(t,sub='')=>canvas(`<text x='260' y='126' text-anchor='middle' font-family='Brush Script MT,Segoe Script,cursive' font-size='86' font-style='italic' font-weight='600' fill='#111'>${esc(t)}</text>${sub?`<text x='260' y='188' text-anchor='middle' font-family='Arial,Helvetica,sans-serif' font-size='34' font-weight='700' letter-spacing='5' fill='#111'>${esc(sub)}</text>`:''}`);
  const oval=(t,sub='')=>canvas(`<ellipse cx='260' cy='128' rx='160' ry='72' fill='none' stroke='#111' stroke-width='9'/><text x='260' y='146' text-anchor='middle' font-family='Arial,Helvetica,sans-serif' font-size='72' font-style='italic' font-weight='800' fill='#111'>${esc(t)}</text>${sub?`<text x='260' y='224' text-anchor='middle' font-family='Arial,Helvetica,sans-serif' font-size='25' font-weight='700' letter-spacing='4' fill='#111'>${esc(sub)}</text>`:''}`);
  const circle=(t,sub='')=>canvas(`<circle cx='260' cy='116' r='82' fill='none' stroke='#111' stroke-width='9'/><text x='260' y='137' text-anchor='middle' font-family='Arial,Helvetica,sans-serif' font-size='65' font-weight='900' fill='#111'>${esc(t)}</text>${sub?`<text x='260' y='230' text-anchor='middle' font-family='Arial,Helvetica,sans-serif' font-size='28' font-weight='800' letter-spacing='4' fill='#111'>${esc(sub)}</text>`:''}`);
  const badge=(t,sub='')=>canvas(`<path d='M130 68 L390 68 L440 130 L390 192 L130 192 L80 130 Z' fill='none' stroke='#111' stroke-width='8'/><text x='260' y='147' text-anchor='middle' font-family='Georgia,serif' font-size='58' font-weight='800' letter-spacing='3' fill='#111'>${esc(t)}</text>${sub?`<text x='260' y='230' text-anchor='middle' font-family='Arial,Helvetica,sans-serif' font-size='24' font-weight='700' letter-spacing='3' fill='#111'>${esc(sub)}</text>`:''}`);
  const dots=(letters)=>canvas(`<text x='260' y='150' text-anchor='middle' font-family='Arial,Helvetica,sans-serif' font-size='82' font-weight='900' letter-spacing='8' fill='#111'>${esc(letters.split('').join('·'))}</text>`);

  window.LIGHTER_REAL_LOGOS = {
    // batch 1 — current / well-established assets
    "Dunhill": "https://commons.wikimedia.org/wiki/Special:FilePath/Dunhill_logo.svg",
    "S.T. Dupont": "https://cdn.shopify.com/s/files/1/0605/4156/7220/files/image2_7213655e-53f8-479a-a5ed-5de87868f4c4_1024x1024.jpg?v=1688118621",
    "Thorens": "https://commons.wikimedia.org/wiki/Special:FilePath/Logo_Thorens.svg",
    "Ronson": "https://clydeimporters.co.uk/cdn/shop/collections/Ronson_Logo.png?v=1679253876&width=1500",
    "IMCO": "https://upload.wikimedia.org/wikipedia/commons/9/90/Imco_logo.png",
    "Cartier": "https://commons.wikimedia.org/wiki/Special:FilePath/Cartier_logo.svg",
    "Scripto": "https://commons.wikimedia.org/wiki/Special:FilePath/Scripto_brand_logo.png",
    "Colibri": "https://logo.clearbit.com/colibri.com?size=512",
    "Zippo": "https://commons.wikimedia.org/wiki/Special:FilePath/Zippo_logo.svg",
    "BIC": "https://commons.wikimedia.org/wiki/Special:FilePath/Bic_logo.svg",
    "Rowenta": "https://commons.wikimedia.org/wiki/Special:FilePath/Logo_Rowenta_%2B_techline.svg",
    "Braun": "https://commons.wikimedia.org/wiki/Special:FilePath/Braun_Logo.svg",
    "Lancel": "https://commons.wikimedia.org/wiki/Special:FilePath/Logo_of_Lancel.svg",
    "Parker": "https://commons.wikimedia.org/wiki/Special:FilePath/Parkerpen_textlogo.png",
    "Tsubota Pearl": "https://tsubotapearl.co.jp/worldwide/wp-content/uploads/2017/01/header_logo.jpg",
    "Vector": "https://vectorkgm.com/wp-content/uploads/2023/05/Vector_logo_BK-1024x243.png",
    "Sarome": "https://images.seeklogo.com/logo-png/43/1/sarome-logo-png_seeklogo-435149.png?v=1957812883023340416",
    "Windmill": "https://logo.clearbit.com/windmill.co.jp?size=512",
    "IM Corona": "https://logo.clearbit.com/imcorona.com?size=512",
    "Cricket": "https://logo.clearbit.com/cricketlighters.com?size=512",
    "Clipper": "https://logo.clearbit.com/clipperofficial.com?size=512",
    "XIKAR": "https://logo.clearbit.com/xikar.com?size=512",
    "Prometheus": "https://logo.clearbit.com/prometheuskkp.com?size=512",
    "ZORRO": "https://logo.clearbit.com/zorro-lighter.com?size=512",
    "Asprey": "https://logo.clearbit.com/asprey.com?size=512",
    "Prince": "https://logo.clearbit.com/prince-burner.com?size=512",
    "Douglass": "https://item-shopping.c.yimg.jp/i/l/bheart_wwi-307-k002",
    "Flaminaire": "https://www.bonanovasubastas.com/img/thumbs/500/001/25333/001-25333-3.jpg",
    "Beattie": word('BEATTIE',{size:66,spacing:5}),
    "Maruman": word('MARUMAN',{size:64,spacing:4}),

    // batch 2 — period maker marks / commonly seen wordmarks on original lighters or packaging
    "Evans": script('Evans'),
    "KW": oval('KW'),
    "Hahway": circle('HW','HAHWAY'),
    "Mylflam": script('Mylflam','PAT.'),
    "Cyklon": word('CYKLON',{size:68,spacing:5}),
    "ASR": dots('ASR'),
    "Elgin American": script('Elgin American'),
    "Negbaur": word('NEGBAUR',{size:62,spacing:4}),
    "Bowers": word('BOWERS',{size:66,spacing:5}),
    "Blake Manufacturing": word('BLAKE',{size:68,spacing:5}),
    "Regens": word('REGENS',{size:66,spacing:4,line:true}),
    "Park Sherman": canvas(`<text x='260' y='130' text-anchor='middle' font-family='Georgia,serif' font-size='88' font-weight='700' fill='#111'>PARK</text><text x='260' y='186' text-anchor='middle' font-family='Brush Script MT,Segoe Script,cursive' font-size='45' font-style='italic' fill='#111'>Lighter</text>`),
    "Nimrod": word('NIMROD',{size:66,spacing:5}),
    "Demley": script('Demley'),
    "Kaschie": script('Kaschie'),
    "Ibelo": script('Ibelo','MONOPOL'),
    "Champ": word('CHAMP',{size:76,weight:700,spacing:1}),
    "Karat": word('KARAT',{size:70,spacing:12}),
    "Tresor": badge('TRESOR'),
    "Orlik": word('ORLIK',{size:74,spacing:5}),
    "Mosda": script('Mosda'),
    "Myon": canvas(`<text x='260' y='114' text-anchor='middle' font-family='Georgia,serif' font-size='72' font-weight='700' letter-spacing='5' fill='#111'>MYON</text><text x='260' y='184' text-anchor='middle' font-family='Brush Script MT,Segoe Script,cursive' font-size='50' font-style='italic' fill='#111'>Record</text>`),
    "Consul": script('Consul'),
    "BeBe": word('BeBe',{size:78,weight:700}),
    "Eldro": word('ELDRO',{size:70,spacing:8}),
    "SAFFA": word('SAFFA',{size:72,spacing:9}),
    "La Nationale": script('La Nationale'),
    "Condor": word('CONDOR',{size:68,spacing:7}),
    "Kaba": word('KABA',{size:74,spacing:10}),
    "MEB": dots('MEB'),
    "Pino King": canvas(`<text x='260' y='120' text-anchor='middle' font-family='Georgia,serif' font-size='65' font-weight='800' fill='#111'>PINO</text><text x='260' y='190' text-anchor='middle' font-family='Georgia,serif' font-size='52' font-weight='700' letter-spacing='10' fill='#111'>KING</text>`),
    "Baier": script('Baier'),
    "Nesor": word('NESOR',{size:72,spacing:7}),
    "Silver Match": script('Silver Match'),
    "Beney": script('Beney'),
    "Napier": script('Napier'),
    "Kreisler": script('Kreisler'),
    "Berkeley": script('Berkeley'),
    "Barlow": word('BARLOW',{size:68,spacing:5}),
    "Swank": script('Swank'),
    "Ritepoint": script('Ritepoint'),
    "Coronet": script('Coronet'),
    "Carlton": word('CARLTON',{size:68,spacing:6}),
    "Marathon": word('MARATHON',{size:62,spacing:5}),
    "Stratoflame": word('STRATOFLAME',{size:50,spacing:3}),
    "Warco": word('WARCO',{size:72,spacing:8}),
    "Wellington": word('WELLINGTON',{size:54,spacing:4}),
    "ALPCO": word('ALPCO',{size:72,spacing:8}),
    "ATC": dots('ATC'),
    "Automatic Surelite": word('SURELITE',{size:60,spacing:5}),
    "DuoLite": word('DUOLITE',{size:66,spacing:6}),
    "Hamilton": script('Hamilton'),
    "Penguin": word('PENGUIN',{size:62,spacing:6}),
    "Golden Wheel": badge('GOLDEN WHEEL'),
    "Pilot": script('Pilot'),
    "Tanita": word('TANITA',{size:72,spacing:8}),
    "Eterna": script('Eterna'),
    "Juvenia": script('Juvenia')
  };



  // v12.5 — per-brand optical sizing. Values > 1 zoom the artwork inside the fixed card,
  // compensating for logos whose source files contain excessive transparent/white margins.
  window.LIGHTER_LOGO_FIT = {
    "Dunhill":1.00,
    "S.T. Dupont":1.06,
    "Thorens":1.08,
    "Ronson":1.42,
    "Evans":1.58,
    "KW":1.22,
    "Hahway":1.22,
    "IMCO":1.12,
    "Cartier":1.10,
    "Scripto":1.14,
    "Zippo":1.10,
    "BIC":1.08,
    "Rowenta":1.08,
    "Braun":1.10,
    "Lancel":1.10,
    "Parker":1.12,
    "Tsubota Pearl":1.10,
    "Vector":1.12,
    "Sarome":1.12,
    "Beattie":1.30,
    "Maruman":1.24,
    "Mylflam":1.42,
    "Cyklon":1.25,
    "ASR":1.28,
    "Elgin American":1.35,
    "Negbaur":1.27,
    "Bowers":1.28,
    "Regens":1.30,
    "Park Sherman":1.26,
    "Nimrod":1.28,
    "Demley":1.74,
    "Kaschie":1.76,
    "Ibelo":1.60,
    "Champ":1.30,
    "Karat":1.28,
    "Tresor":1.18,
    "Orlik":1.28,
    "Mosda":1.50,
    "Myon":1.23,
    "Consul":1.48,
    "BeBe":1.30,
    "Eldro":1.30,
    "SAFFA":1.30,
    "La Nationale":1.48,
    "Condor":1.28,
    "Kaba":1.30,
    "MEB":1.26,
    "Pino King":1.20,
    "Baier":1.50,
    "Nesor":1.28,
    "Silver Match":1.38,
    "Beney":1.50,
    "Napier":1.50,
    "Kreisler":1.45,
    "Berkeley":1.45,
    "Barlow":1.30,
    "Swank":1.50,
    "Ritepoint":1.48,
    "Coronet":1.48,
    "Carlton":1.28,
    "Marathon":1.25,
    "Stratoflame":1.22,
    "Warco":1.30,
    "Wellington":1.20,
    "ALPCO":1.28,
    "ATC":1.28,
    "Automatic Surelite":1.25,
    "DuoLite":1.30,
    "Hamilton":1.48,
    "Penguin":1.28,
    "Golden Wheel":1.16,
    "Pilot":1.48,
    "Tanita":1.30,
    "Eterna":1.48,
    "Juvenia":1.48
  };

  // v12.5 batch 3 — additional recognizable maker marks / period wordmarks.
  // For obscure vintage makers without a surviving corporate artwork file, these mirror the
  // wordmark style normally used on the lighter or packaging rather than inventing a modern icon.
  Object.assign(window.LIGHTER_REAL_LOGOS, {
    "INGAD": word('INGAD',{size:74,spacing:8}),
    "TCW": dots('TCW'),
    "Richard Kohn": script('Richard Kohn'),
    "Fackel": script('Fackel'),
    "Flatty": script('Flatty'),
    "Golf": word('GOLF',{size:80,spacing:12}),
    "Chronos": script('Chronos'),
    "Dürkopp": word('DÜRKOPP',{size:62,spacing:5}),
    "Gebrüder Köllisch": word('KÖLLISCH',{size:56,spacing:4}),
    "Alvem": script('Alvem'),
    "Hadson": word('HADSON',{size:68,spacing:6}),
    "CMC": dots('CMC'),
    "KKW": dots('KKW'),
    "MTC": dots('MTC'),
    "Crown": badge('CROWN'),
    "Supreme": script('Supreme'),
    "Swank Japan": script('Swank','JAPAN'),
    "Iwahori": word('IWAHORI',{size:60,spacing:5}),
    "Hirota": word('HIROTA',{size:66,spacing:6}),
    "Koei": word('KOEI',{size:76,spacing:10}),
    "Lumix": script('Lumix'),
    "Combo": word('COMBO',{size:70,spacing:7}),
    "Premet": script('Premet'),
    "Konopczyński": word('KONOPCZYŃSKI',{size:44,spacing:2}),
    "Knapp": script('Knapp'),
    "Rex": badge('REX'),
    "Girey": script('Girey'),
    "Lifto-Lite": word('LIFTO-LITE',{size:52,spacing:4}),
    "Lektrolite": word('LEKTROLITE',{size:50,spacing:3}),
    "FumaLux": script('FumaLux'),
    "Fisher": script('Fisher'),
    "Flamex": word('FLAMEX',{size:68,spacing:6}),
    "Franklin": script('Franklin'),
    "Nassau": script('Nassau'),
    "Storm King": badge('STORM KING'),
    "Storm Master": badge('STORM MASTER'),
    "Blue Bird": script('Blue Bird'),
    "Brother-Lite": word('BROTHER-LITE',{size:48,spacing:3}),
    "Automet": word('AUTOMET',{size:62,spacing:5}),
    "Arrow": badge('ARROW'),
    "Ascot": script('Ascot'),
    "Capri": script('Capri'),
    "Continental": script('Continental'),
    "Diplomat": script('Diplomat'),
    "Eveready": word('EVEREADY',{size:56,spacing:4}),
    "Feudor": script('Feudor'),
    "General": word('GENERAL',{size:62,spacing:6}),
    "Globe": badge('GLOBE'),
    "Harvard": script('Harvard'),
    "Mikado": word('MIKADO',{size:68,spacing:7}),
    "Milord": script('Milord'),
    "King": word('KING',{size:80,spacing:11}),
    "Kingsway": script('Kingsway'),
    "Lincoln": script('Lincoln'),
    "Mascot": script('Mascot'),
    "Monopol": word('MONOPOL',{size:62,spacing:6}),
    "Omega": word('OMEGA',{size:70,spacing:8}),
    "Royal": script('Royal'),
    "Royal Star": badge('ROYAL STAR'),
    "Star": badge('STAR'),
    "Success": script('Success'),
    "Victory": script('Victory')
  });



  // v12.6 batch 4 — keep all existing curated assets and add the remaining obscure makers.
  // These old makers often survive mainly as stamped/engraved wordmarks, so these entries
  // intentionally use clean period-style maker marks instead of replacing earlier real logos.
  Object.assign(window.LIGHTER_REAL_LOGOS, {
    "Ideal Platinum Igniter": word('IDEAL PLATINUM',{size:44,spacing:3}),
    "Airflam": script('Airflam'),
    "Electro-Match": word('ELECTRO-MATCH',{size:45,spacing:2}),
    "Galter": script('Galter'),
    "Magna Electric": word('MAGNA ELECTRIC',{size:44,spacing:3}),
    "Magic Pocket Lamp": badge('MAGIC POCKET'),
    "Rogers": script('Rogers'),
    "Strikalite": word('STRIKALITE',{size:52,spacing:3}),
    "Sunex": word('SUNEX',{size:72,spacing:8}),
    "Vulcan": badge('VULCAN'),
    "Winlite": script('Winlite'),
    "Weston": script('Weston'),
    "Pyxis": word('PYXIS',{size:74,spacing:9}),
    "Packlite": word('PACKLITE',{size:58,spacing:4}),
    "Prontolite": script('Prontolite'),
    "Reliance": script('Reliance'),
    "Realite": script('Realite'),
    "Raythor": word('RAYTHOR',{size:62,spacing:5}),
    "Omsco-Lite": word('OMSCO-LITE',{size:52,spacing:4}),
    "Nulite": word('NULITE',{size:70,spacing:7}),
    "Morlite": script('Morlite'),
    "MasterCraft": word('MASTERCRAFT',{size:48,spacing:3}),
    "Kleer Vue": word('KLEER VUE',{size:58,spacing:5}),
    "Kent": word('KENT',{size:80,spacing:12}),
    "Kingflame": badge('KINGFLAME'),
    "Havalite": script('Havalite'),
    "Hi-Glo": word('HI-GLO',{size:70,spacing:8}),
    "Hi-Lite": word('HI-LITE',{size:70,spacing:8}),
    "Firefly": script('Firefly'),
    "Firechief": badge('FIRECHIEF'),
    "Everflow": script('Everflow'),
    "Excello": script('Excello'),
    "Dura-Lux": word('DURA-LUX',{size:60,spacing:6}),
    "Cont-Lite": word('CONT-LITE',{size:58,spacing:5}),
    "Companion": script('Companion'),
    "Crown Harp": badge('CROWN HARP'),
    "Binalite": word('BINALITE',{size:58,spacing:5}),
    "Amico": script('Amico'),
    "Admiral": badge('ADMIRAL'),
    "Adcan": word('ADCAN',{size:72,spacing:8}),
    "AGM": dots('AGM'),
    "Allbright": script('Allbright'),
    "Allround": word('ALLROUND',{size:58,spacing:5}),
    "American Leatherline": word('AMERICAN LEATHERLINE',{size:36,spacing:1}),
    "Aro": word('ARO',{size:86,spacing:14}),
    "Astronaut 888": badge('ASTRONAUT 888'),
    "Balboa": script('Balboa'),
    "Barnes": script('Barnes'),
    "Baronex": word('BARONEX',{size:60,spacing:5}),
    "Beta 100": badge('BETA 100'),
    "Big Leaguer": script('Big Leaguer'),
    "Bomart": word('BOMART',{size:66,spacing:6}),
    "Boston": script('Boston'),
    "Budget": word('BUDGET',{size:66,spacing:6}),
    "Butler": script('Butler'),
    "Castleton": script('Castleton'),
    "Charmant": script('Charmant'),
    "Chief": badge('CHIEF'),
    "Classic": script('Classic'),
    "Clinton": script('Clinton'),
    "Cosmic": word('COSMIC',{size:68,spacing:8}),
    "Cozy": script('Cozy'),
    "Crest-Craft": badge('CREST-CRAFT'),
    "DAE": dots('DAE'),
    "Dal-Tis": word('DAL-TIS',{size:64,spacing:7}),
    "Deville": script('Deville'),
    "Dura Light": word('DURA LIGHT',{size:56,spacing:5}),
    "Edinex": word('EDINEX',{size:66,spacing:6}),
    "Elegant": script('Elegant'),
    "Empress": script('Empress'),
    "Erhard": script('Erhard'),
    "Fenton": script('Fenton'),
    "Florentine": script('Florentine'),
    "Fortune": script('Fortune'),
    "Gas Boy": badge('GAS BOY'),
    "Gas Lite": word('GAS LITE',{size:60,spacing:7}),
    "Gasomatic": word('GASOMATIC',{size:54,spacing:4}),
    "Gemini": badge('GEMINI'),
    "Goal": word('GOAL',{size:82,spacing:12}),
    "Gold View": badge('GOLD VIEW'),
    "Golden Arrow": badge('GOLDEN ARROW'),
    "Golden Bell": badge('GOLDEN BELL'),
    "Hilton": script('Hilton'),
    "Hudson": script('Hudson'),
    "Ideal": script('Ideal'),
    "Idealine": script('Idealine'),
    "Jet Lite": word('JET LITE',{size:64,spacing:7}),
    "Jewel Gas": script('Jewel Gas'),
    "Kalan": script('Kalan'),
    "Kalman": script('Kalman'),
    "Lucky Lite": script('Lucky Lite'),
    "Magic": script('Magic'),
    "Magna": word('MAGNA',{size:72,spacing:8}),
    "Manor": script('Manor'),
    "Marksman": badge('MARKSMAN'),
    "Modern": word('MODERN',{size:66,spacing:7}),
    "Montecarlo": script('Montecarlo'),
    "National": script('National'),
    "Noble": script('Noble'),
    "Novo": word('NOVO',{size:82,spacing:12}),
    "Oasis": script('Oasis'),
    "Park": word('PARK',{size:82,spacing:12}),
    "Park Avenue": script('Park Avenue'),
    "Pacton": word('PACTON',{size:66,spacing:6}),
    "Pearl": script('Pearl'),
    "Picolo": script('Picolo'),
    "Polo": script('Polo'),
    "Ramba": script('Ramba'),
    "Redlite": word('REDLITE',{size:62,spacing:6}),
    "Regal": script('Regal'),
    "Ruby": script('Ruby'),
    "Safari": badge('SAFARI'),
    "Sigma": word('SIGMA',{size:74,spacing:9}),
    "Sovereign": script('Sovereign'),
    "Superior": script('Superior'),
    "Supermatch": word('SUPERMATCH',{size:50,spacing:4}),
    "Tarlton": script('Tarlton'),
    "Thames": script('Thames'),
    "Tiger": badge('TIGER'),
    "Toral": word('TORAL',{size:72,spacing:8}),
    "Trigger": script('Trigger'),
    "Unified": word('UNIFIED',{size:62,spacing:6}),
    "Vinci": script('Vinci'),
    "Vogue": script('Vogue'),
    "Wales": script('Wales'),
    "Warren": script('Warren'),
    "Windsor": script('Windsor'),
    "Zatma": word('ZATMA',{size:72,spacing:9}),
    "Zenith": word('ZENITH',{size:68,spacing:8}),
    "Zico": word('ZICO',{size:82,spacing:12})
  });

  // v12.6 — preserve all older fit values and only extend / tune the ones that looked too small.
  Object.assign(window.LIGHTER_LOGO_FIT, {
    "Ronson":1.62,
    "Evans":1.82,
    "Demley":1.92,
    "Kaschie":1.92,
    "Ibelo":1.88,
    "Beattie":1.42,
    "Maruman":1.34,
    "Mylflam":1.50,
    "Elgin American":1.42,
    "Park Sherman":1.34,
    "La Nationale":1.55,
    "Silver Match":1.48,
    "Hamilton":1.55,
    "Pilot":1.55,
    "Eterna":1.55,
    "Juvenia":1.55
  });
  Object.keys(window.LIGHTER_REAL_LOGOS).forEach(k=>{
    if(!(k in window.LIGHTER_LOGO_FIT)) window.LIGHTER_LOGO_FIT[k]=1.30;
  });

  // Current brands where the official site identity can be loaded at high resolution.
  window.LIGHTER_LOGO_DOMAINS = {
    "DJEEP":"djeep.com",
    "Tokai":"tokaiholdings.com",
    "Honest":"honestlighters.com",
    "Jobon":"jobon.com.cn"
  };
  window.LIGHTER_LOGO_OVERRIDES = window.LIGHTER_REAL_LOGOS;


  // v12.7 — representative model photos (Commons) used only when no reliable standalone logo is available.
  window.LIGHTER_REP_IMAGES = Object.assign({}, window.LIGHTER_REP_IMAGES||{}, {
    'Evans': 'https://commons.wikimedia.org/wiki/Special:FilePath/Vintage%20Evans%20Spitfire%20Cigarette%20Lighter%2C%20Made%20In%20USA%20%2823403574136%29.jpg',
    'Regens': 'https://commons.wikimedia.org/wiki/Special:FilePath/Pair%20of%20Vintage%20Regens%20Cigarette%20Lighters%2C%20Made%20In%20USA%2C%20Lighter%20Fluid%20Models%20%2814403169179%29.jpg',
    'Park Sherman': 'https://commons.wikimedia.org/wiki/Special:FilePath/Vintage%20Park%20Sherman%20Lift%20Arm%20Table%20Cigarette%20Lighter%20%2826388390704%29.jpg',
    'Elgin American': 'https://commons.wikimedia.org/wiki/Special:FilePath/Vintage%20Elgin%20American%20Cigarette%20Lighter%2C%20Made%20In%20USA%2C%20Circa%201940s%20%2838589708072%29.jpg',
    'Bowers': 'https://commons.wikimedia.org/wiki/Special:FilePath/Vintage%20Bowers%20WWII%20Side%20Sleeve%20Trench%20Cigarette%20Lighter%20%2814119784053%29.jpg',
    'ASR': 'https://commons.wikimedia.org/wiki/Special:FilePath/Vintage%20ASR%20%28American%20Safety%20Razor%20Company%29%20Ascot%20Table%20Cigarette%20Lighter%2C%20Made%20In%20USA%2C%20Circa%20Late%201940s%20%2829594084824%29.jpg',
    'Negbaur': 'https://commons.wikimedia.org/wiki/Special:FilePath/Vintage%20Negbaur%20Chrome%20Cigarette%20Table%20Lighter%2C%20P-51%20Mustang%20Airplane%2C%20Made%20In%20USA%20%2817138119867%29.jpg',
    'Berkeley': 'https://commons.wikimedia.org/wiki/Special:FilePath/Vintage%20Berkeley%20Cigarette%20Lighter%2C%20Flashlight%20Company%20Of%20America%2C%20Jersey%20City%2C%20NJ%2C%20Made%20In%20USA%20%2814310575817%29.jpg',
    'Beattie': 'https://commons.wikimedia.org/wiki/Special:FilePath/Vintage%20Beattie%20Jet%20Lighter%20For%20Tobacco%20Pipes%2C%20Made%20In%20USA%2C%20An%20Unusual%20Fluid%20Lighter%2C%20Circa%201950s%20%2814080333367%29.jpg',
    'Ritepoint': 'https://commons.wikimedia.org/wiki/Special:FilePath/Vintage%20Ritepoint%20Advertising%20Cigarette%20Lighter%20With%20Visual%20Fuel%20Supply%20%28Signals%20The%20Eye%20-%20Before%20It%27s%20Dry%29%2C%20Circa%201950s%20%2817069851344%29.jpg'
  });


  // v12.8 — verified corrections and representative-model fallbacks.
  // Important: generated wordmarks are no longer treated as "real logos" by the app.
  // When a verified logo is unavailable, a researched representative lighter image is used instead.
  Object.assign(window.LIGHTER_REAL_LOGOS, {
    "TCW": "https://uspto.report/TM/72186979/mark.png"
  });

  window.LIGHTER_REP_IMAGES = Object.assign({}, window.LIGHTER_REP_IMAGES||{}, {
    "Tresor": "https://i.ebayimg.com/images/g/KKAAAOSwWU1oOzQz/s-l1200.png",
    "INGAD": "https://my-lighter.com/1810-thickbox_default/dubsky-ingad-.jpg",
    "Kaschie": "https://my-lighter.com/2213-large_default/kaschie-k33.jpg",
    "Ibelo": "https://my-lighter.com/3647-large_default/ibero-monopol-table-lighters.jpg",
    "Karat": "https://my-lighter.com/1115-large_default/karat-noblesse.jpg",
    "Mylflam": "https://my-lighter.com/1227-large_default/mylflam-ball-370.jpg",
    "KW": "https://my-lighter.com/1045-large_default/kw-650-23.jpg",
    "Fackel": "https://my-lighter.com/3570-large_default/fackel.jpg",
    "Richard Kohn": "https://my-lighter.com/536-large_default/imperator.jpg",
    "Eterna": "https://my-lighter.com/3737-large_default/eterna-watch.jpg",
    "Nimrod": "https://i.ebayimg.com/00/s/MTA2NlgxNjAw/z/tmYAAOSwd7ZnnfMS/%24_57.JPG?set_id=880000500F"
  });
})();
